namespace PoWatch.Shared.Models;

/// <summary>Request parameters for generating a Handoff Coach brief.</summary>
public sealed class GenerateHandoffBriefRequestDto
{
    /// <summary>FullDay | Morning | Afternoon | Night</summary>
    public string ShiftWindow { get; init; } = "FullDay";

    /// <summary>NurseToNurse | Supervisor | FamilySafe</summary>
    public string Audience { get; init; } = "NurseToNurse";

    public bool IncludeUnresolvedAlerts { get; init; } = true;
    public bool IncludeHighlights { get; init; } = true;
}

/// <summary>A generated handoff brief produced by the Handoff Coach feature.</summary>
public sealed class HandoffBriefDto
{
    public DateOnly Date { get; init; }
    public string Audience { get; init; } = string.Empty;
    public string ShiftWindow { get; init; } = string.Empty;

    /// <summary>Start of the covered window, inclusive — the local hours the brief actually describes.</summary>
    public DateTimeOffset WindowStartUtc { get; init; }

    /// <summary>End of the covered window, exclusive.</summary>
    public DateTimeOffset WindowEndUtc { get; init; }

    // The counts the brief was written from. Surfacing them lets the UI show what the prose is based
    // on, so a caregiver can reconcile the brief against the timeline instead of taking it on trust.
    public int TotalEvents { get; init; }
    public int OutlierCount { get; init; }
    public int SignificantCount { get; init; }

    /// <summary>2–4 sentence overview of the shift.</summary>
    public string Summary { get; init; } = string.Empty;

    /// <summary>Ordered list of items requiring immediate attention or handoff.</summary>
    public IReadOnlyList<string> PriorityItems { get; init; } = [];

    /// <summary>Items that need follow-up during the next shift.</summary>
    public IReadOnlyList<string> FollowUps { get; init; } = [];

    /// <summary>Citations or source snippets from observation data used to generate the brief.</summary>
    public IReadOnlyList<string> SourceNotes { get; init; } = [];

    /// <summary>True when the summary was generated by Azure OpenAI; false when produced by the template engine.</summary>
    public bool IsAiGenerated { get; init; }

    public DateTimeOffset GeneratedAtUtc { get; init; }
}
