using Microsoft.Extensions.Logging;
using PoWatch.Application.Contracts;
using PoWatch.Domain.Models;

namespace PoWatch.Application.Services;

/// <summary>
/// Coordinates recording, listing, deletion, and retention for handoff voice memos. The
/// retention window is hard-coded at <see cref="HandoffMemo.RetentionDays"/> per product
/// decision — config knobs were considered and rejected because every operator changing the
/// window is a code change, and the number reflects a policy promise to caregivers.
/// </summary>
public sealed class HandoffMemoService(
    IHandoffMemoRepository repository,
    IHandoffMemoStore store,
    ILogger<HandoffMemoService> logger)
{
    /// <summary>Upload a recorded memo. The <paramref name="memoId"/> is generated by the caller
    /// so the API endpoint can return it before the bytes finish uploading; the service stores
    /// it verbatim.</summary>
    public async Task<HandoffMemo> RecordAsync(
        string memoId,
        SubjectId? subjectId,
        string contentType,
        int durationMs,
        byte[] bytes,
        string? authorUserId,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(memoId))
            throw new InvalidOperationException("MemoId is required.");
        if (bytes is null || bytes.Length == 0)
            throw new InvalidOperationException("Memo bytes are empty.");
        if (durationMs < 0)
            throw new InvalidOperationException("DurationMs cannot be negative.");

        logger.LogInformation(
            "Recording handoff memo. MemoId={MemoId} SubjectId={SubjectId} DurationMs={DurationMs} SizeBytes={SizeBytes} AuthorUserId={AuthorUserId}",
            memoId,
            subjectId,
            durationMs,
            bytes.Length,
            authorUserId ?? "anonymous");

        var blobPath = await store.UploadAsync(memoId, contentType, bytes, cancellationToken);

        var memo = new HandoffMemo
        {
            Id = memoId,
            SubjectId = subjectId,
            BlobPath = blobPath,
            DurationMs = durationMs,
            ContentType = contentType,
            CreatedAtUtc = DateTimeOffset.UtcNow,
            AuthorUserId = authorUserId
        };

        var stored = await repository.AddAsync(memo, cancellationToken);
        return stored;
    }

    public Task<HandoffMemo?> GetAsync(string id, CancellationToken cancellationToken) =>
        repository.GetAsync(id, cancellationToken);

    public Task<IReadOnlyList<HandoffMemo>> ListRecentAsync(int limit, CancellationToken cancellationToken) =>
        repository.ListRecentAsync(limit, cancellationToken);

    public async Task<bool> DeleteAsync(string id, string? actorUserId, CancellationToken cancellationToken)
    {
        var memo = await repository.GetAsync(id, cancellationToken);
        if (memo is null) return false;

        await repository.DeleteAsync(id, cancellationToken);
        await store.DeleteAsync(memo.BlobPath, cancellationToken);

        logger.LogInformation(
            "Handoff memo deleted. MemoId={MemoId} AuthorUserId={AuthorUserId}",
            id,
            actorUserId ?? "anonymous");
        return true;
    }

    /// <summary>Delete every memo older than <see cref="HandoffMemo.RetentionDays"/> days.
    /// Idempotent — re-running deletes only the still-expired rows.</summary>
    public async Task<int> PurgeExpiredAsync(CancellationToken cancellationToken)
    {
        var cutoff = DateTimeOffset.UtcNow.AddDays(-HandoffMemo.RetentionDays);
        var expired = await repository.ListOlderThanAsync(cutoff, cancellationToken);
        if (expired.Count == 0) return 0;

        foreach (var memo in expired)
        {
            await repository.DeleteAsync(memo.Id, cancellationToken);
            await store.DeleteAsync(memo.BlobPath, cancellationToken);
        }

        logger.LogInformation(
            "Handoff memo retention sweep. CutoffUtc={CutoffUtc} DeletedCount={DeletedCount} RetentionDays={RetentionDays}",
            cutoff,
            expired.Count,
            HandoffMemo.RetentionDays);
        return expired.Count;
    }
}
